// src/routes/authentication/+page.svelte
<script>
  import { enhance } from "$app/forms";
  import { getDoc, doc } from "firebase/firestore";
  // import { registerUser, signInUser } from '../../lib/firebase/db/client/auth'
  import { auth } from '../../lib/firebase/firebase.app'
  import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from "firebase/auth";
  import { fail, redirect } from "@sveltejs/kit";

  export let form;

  let register = false;
  let authenticating = false;
  let email = "";
  let password = "";
  let confirmPass = "";
  let error = false;

  async function handleAuthenticate() {
    if(authenticating){
      return;
    }

    if (!email || !password || (register && !confirmPass)){
      error = true;
      console.log("invalid inputs");
      return;
    }

    authenticating = true;

    try {
      if (!register){
        try{
          const userCredential = await signInWithEmailAndPassword(
          auth,
          email,
          password,
          );

          const user = userCredential.user;

          const token = await user.getIdToken();

          const response = await fetch('/api/login', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({ token })
          });

          if (response.ok) {
            error = false;
            window.location.href = "/dashboard";
          } else {
            console.error('Login failed');
          }
        }
        catch(err){
          error = true;
          console.error("Error logging in user:", err);
        }
      }
    } catch (err) {
      error = true;
      console.log('There was an auth error', err);
      authenticating = false;
    }
  }

  function handleRegister() {
    register = !register;
  }
</script>

<div class="py-32 w-screen flex flex-row justify-center">
  <div
    class=" w-1/2 flex flex-col justify-self-center justify-items-center gap-4"
  >
    <form
      class="flex flex-col justify-start w-full gap-2"
      method="POST"
      action="?/handleAuth"
      use:enhance
    >
      <h1 class="text-white text-center text-2xl font-semibold py-2">
        {register ? "Register" : "Login"}
      </h1>
      {#if error}
        <p class="text-center text-red-500 font-semibold">The information you have entered is not correct</p>
      {/if}
      <div class="flex flex-row justify-center">
        <input
          bind:value={email}
          type="email"
          id="email"
          name="email"
          placeholder="Email"
          class="w-1/2 mx-2 p-2 rounded-md"
        />
      </div>
      <div class="flex flex-row justify-center">
        <input
          bind:value={password}
          type="password"
          id="password"
          name="password"
          placeholder="Password"
          class="w-1/2 mx-2 p-2 rounded-md"
        />
      </div>
      {#if register}
        <div class="flex flex-row justify-center">
          <input
            bind:value={confirmPass}
            type="password"
            name="confirmPass"
            placeholder="Confirm Password"
            class="w-1/2 mx-2 p-2 rounded-md"
          />
        </div>
      {/if}

      <input type="hidden" id="register" name="register" value={register} />

      <div class="flex flex-row justify-center">
        <button on:click={handleAuthenticate} type="submit" class="w-1/2 btn btn-primary">
          <!-- {#if authenticating}
            <i class="fa-solid fa-spinner spin"/>
          {:else}
              Submit
          {/if} -->
          Submit
        </button>
      </div>
    </form>

    <div class="flex flex-row justify-center">
      {#if register}
        <div class="flex flex-row">
          <p class="text-lg text-white font-semibold px-1">
            Already have an account?
          </p>
          <button
            on:click={handleRegister}
            on:keydown={() => {}}
            class="text-lg text-primary font-semibold"
          >
            Login</button
          >
        </div>
      {:else}
        <div class="flex flex-row">
          <p class="text-lg text-white font-semibold px-1">
            Don't have an account?
          </p>
          <button
            on:click={handleRegister}
            on:keydown={() => {}}
            class="text-lg text-primary font-semibold"
          >
            Register</button
          >
        </div>
      {/if}
    </div>
  </div>
</div>

// src/routes/authentication.tsx
import {zodResolver} from '@hookform/resolvers/zod'
import {createFileRoute, useNavigate} from '@tanstack/react-router'
import {
	createUserWithEmailAndPassword,
	signInWithEmailAndPassword
} from 'firebase/auth'
import {useState} from 'react'
import {useForm} from 'react-hook-form'
import {z} from 'zod'
import {BrandLogo} from '@/components/ui'
import GreenCard from '@/components/ui/GreenCard'
import GreyButton from '@/components/ui/GreyButton'
import GrnButton from '@/components/ui/GrnButton'
import {PageContainer} from '@/components/ui/page-container'
import TitleCard from '@/components/ui/TitleCard'
import {auth} from '$lib/firebase/firebase.app'
import {useAuth} from '../context/AuthContext'

const loginSchema = z.object({
	email: z.string().email('Invalid email address'),
	password: z.string().min(6, 'Password must be at least 6 characters')
})

const signupSchema = z
	.object({
		username: z.string().min(2, 'Username must be at least 2 characters'),
		email: z.string().email('Invalid email address'),
		password: z.string().min(6, 'Password must be at least 6 characters'),
		confirmPassword: z.string()
	})
	.refine(data => data.password === data.confirmPassword, {
		message: "Passwords don't match",
		path: ['confirmPassword']
	})

type LoginFormValues = z.infer<typeof loginSchema>
type SignupFormValues = z.infer<typeof signupSchema>

export const Route = createFileRoute('/authentication')({
	component: AuthenticationComponent
})

function AuthenticationComponent() {
	const {loading} = useAuth()
	const [isSignUp, setIsSignUp] = useState(false)
	const [authError, setAuthError] = useState('')
	const navigate = useNavigate()

	const loginForm = useForm<LoginFormValues>({
		resolver: zodResolver(loginSchema),
		defaultValues: {
			email: '',
			password: ''
		}
	})

	const signupForm = useForm<SignupFormValues>({
		resolver: zodResolver(signupSchema),
		defaultValues: {
			username: '',
			email: '',
			password: '',
			confirmPassword: ''
		}
	})

	if (loading) {
		return (
			<div className='flex min-h-screen items-center justify-center bg-linear-to-b from-green-100 to-green-50'>
				<span className='loading loading-spinner loading-lg' />
			</div>
		)
	}

	const onLogin = async (values: LoginFormValues) => {
		setAuthError('')
		try {
			const userCredential = await signInWithEmailAndPassword(
				auth,
				values.email,
				values.password
			)

			const idToken = await userCredential.user.getIdToken()

			const sessionResponse = await fetch('/api/auth/sessionLogin', {
				method: 'POST',
				headers: {'Content-Type': 'application/json'},
				body: JSON.stringify({idToken})
			})

			if (sessionResponse.ok) {
				window.location.reload()
			} else {
				const data = await sessionResponse.json()
				setAuthError(data.error || 'Failed to create session')
			}
		} catch (error: unknown) {
			if (error instanceof Error) {
				if (error.message.includes('auth/invalid-credential')) {
					setAuthError('Invalid email or password')
				} else if (error.message.includes('auth/user-not-found')) {
					setAuthError('User not found')
				} else {
					setAuthError(error.message)
				}
			} else {
				setAuthError('Login failed')
			}
		}
	}

	const onSignUp = async (values: SignupFormValues) => {
		setAuthError('')
		try {
			const registerResponse = await fetch('/api/auth/register', {
				method: 'POST',
				headers: {'Content-Type': 'application/json'},
				body: JSON.stringify({
					username: values.username,
					email: values.email,
					password: values.password,
					confirmPassword: values.confirmPassword
				})
			})

			const registerData = await registerResponse.json()

			if (!registerResponse.ok) {
				setAuthError(registerData.error || 'Registration failed')
				return
			}

			const userCredential = await createUserWithEmailAndPassword(
				auth,
				values.email,
				values.password
			)

			const idToken = await userCredential.user.getIdToken()

			const sessionResponse = await fetch('/api/auth/sessionLogin', {
				method: 'POST',
				headers: {'Content-Type': 'application/json'},
				body: JSON.stringify({idToken})
			})

			if (sessionResponse.ok) {
				window.location.href = '/signup/about-you'
			} else {
				const data = await sessionResponse.json()
				setAuthError(data.error || 'Failed to create session')
			}
		} catch (error: unknown) {
			if (error instanceof Error) {
				if (error.message.includes('auth/email-already-in-use')) {
					setAuthError('Email already in use')
				} else {
					setAuthError(error.message)
				}
			} else {
				setAuthError('Registration failed')
			}
		}
	}

	return (
		<PageContainer>
			<BrandLogo
				direction='vertical'
				gapClassName='gap-0'
				showTitle={true}
				size='lg'
				titleClassName='font-kapakana text-[75px] leading-none tracking-normal [word-spacing:0.40em]'
				titlePosition='above'
				titleSpacing={-55}
			/>
			<TitleCard>
				<h1>{isSignUp ? 'Sign Up' : 'Sign In'}</h1>
			</TitleCard>
			<GreenCard className='flex max-w-full! flex-col'>
				{authError && (
					<div className='alert alert-error'>
						<span>{authError}</span>
					</div>
				)}

				{isSignUp ? (
					<form
						className='space-y-4'
						onSubmit={signupForm.handleSubmit(onSignUp)}
					>
						<div className='form-control flex flex-col'>
							<label className='label' htmlFor='signup-username'>
								<span className='label-text'>Username</span>
							</label>
							<input
								className='input input-bordered w-full'
								id='signup-username'
								placeholder='johndoe'
								type='text'
								{...signupForm.register('username')}
							/>
							{signupForm.formState.errors.username && (
								<div className='label'>
									<span className='label-text-alt text-error'>
										{signupForm.formState.errors.username.message}
									</span>
								</div>
							)}
						</div>

						<div className='form-control flex flex-col gap-1'>
							<label className='label' htmlFor='signup-email'>
								<span className='label-text'>Email</span>
							</label>
							<input
								className='input input-bordered w-full'
								id='signup-email'
								placeholder='john@example.com'
								type='email'
								{...signupForm.register('email')}
							/>
							{signupForm.formState.errors.email && (
								<div className='label'>
									<span className='label-text-alt text-error'>
										{signupForm.formState.errors.email.message}
									</span>
								</div>
							)}
						</div>

						<div className='form-control flex flex-col'>
							<label className='label' htmlFor='signup-password'>
								<span className='label-text'>Password</span>
							</label>
							<input
								className='input input-bordered w-full'
								id='signup-password'
								type='password'
								{...signupForm.register('password')}
							/>
							{signupForm.formState.errors.password && (
								<div className='label'>
									<span className='label-text-alt text-error'>
										{signupForm.formState.errors.password.message}
									</span>
								</div>
							)}
						</div>

						<div className='form-control flex flex-col'>
							<label className='label' htmlFor='signup-confirm-password'>
								<span className='label-text'>Confirm Password</span>
							</label>
							<input
								className='input input-bordered w-full'
								id='signup-confirm-password'
								type='password'
								{...signupForm.register('confirmPassword')}
							/>
							{signupForm.formState.errors.confirmPassword && (
								<div className='label'>
									<span className='label-text-alt text-error'>
										{signupForm.formState.errors.confirmPassword.message}
									</span>
								</div>
							)}
						</div>

						<GrnButton type='submit'>Create Account</GrnButton>
					</form>
				) : (
					<form
						className='space-y-4'
						onSubmit={loginForm.handleSubmit(onLogin)}
					>
						<div className='form-control flex flex-col'>
							<label className='label' htmlFor='login-email'>
								<span className='label-text'>Email</span>
							</label>
							<input
								className='input input-bordered w-full'
								id='login-email'
								placeholder='john@example.com'
								type='email'
								{...loginForm.register('email')}
							/>
							{loginForm.formState.errors.email && (
								<div className='label'>
									<span className='label-text-alt text-error'>
										{loginForm.formState.errors.email.message}
									</span>
								</div>
							)}
						</div>

						<div className='form-control flex flex-col'>
							<label className='label' htmlFor='login-password'>
								<span className='label-text'>Password</span>
							</label>
							<input
								className='input input-bordered w-full'
								id='login-password'
								type='password'
								{...loginForm.register('password')}
							/>
							{loginForm.formState.errors.password && (
								<div className='label'>
									<span className='label-text-alt text-error'>
										{loginForm.formState.errors.password.message}
									</span>
								</div>
							)}
						</div>

						<GrnButton type='submit'>Sign In</GrnButton>
					</form>
				)}
			</GreenCard>

			<div className='flex w-[22.5rem] flex-col items-center text-center'>
				<div className='divider'>OR</div>
				<GreyButton
					onClick={() => {
						setIsSignUp(!isSignUp)
						setAuthError('')
						loginForm.reset()
						signupForm.reset()
					}}
					type='button'
				>
					{isSignUp ? 'Sign In' : 'Sign Up'}
				</GreyButton>

				<div className='divider'>OR</div>
				<GreyButton onClick={() => navigate({to: '/guest'})} type='button'>
					Continue as Guest
				</GreyButton>
			</div>
		</PageContainer>
	)
}
